name: 'ServiceNow DevOps Change Update'
description: 'Update Change Request in ServiceNow DevOps'
inputs:
  devops-integration-user-name:
    description: 'DevOps Integration User Name'
    required: true
  devops-integration-user-pass:
    description: 'DevOps Integration User Pass'
    required: true
  instance-name: 
    description: 'ServiceNow Instance Name (e.g.: rapdevio)'
    required: true
  context-github:
    description: 'Github context'
    required: true
  change-number:
    description: 'ServiceNow change number'
    required: true
  change-state:
    description: 'ServiceNow change state'
    required: true
  change-result:
    description: 'ServiceNow change result'
    required: true
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
runs: 
  using: 'node12'
  main: 'dist/index.js'
